const SkillsArray = [
  { value: "Furniture", label: "Furniture" },
  { value: "Electronics", label: "Electronics" },
  { value: "Home Cooking", label: "Home Cooking" },
  { value: "Baking", label: "Baking" },
  { value: "Cake Decorating", label: "Cake Decorating" },
  { value: "Pastry Making", label: "Pastry Making" },
  { value: "Dessert Art", label: "Dessert Art" },
  { value: "Food Plating", label: "Food Plating" },
  { value: "Gourmet Cooking", label: "Gourmet Cooking" },
  { value: "Handmade Chocolates", label: "Handmade Chocolates" },
  { value: "Custom Cakes", label: "Custom Cakes" },
  { value: "Artisan Bread", label: "Artisan Bread" },
  { value: "Handmade Art", label: "Handmade Art" },
  { value: "Painting", label: "Painting" },
  { value: "Sketching", label: "Sketching" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "DIY Crafts", label: "DIY Crafts" },
  { value: "Paper Craft", label: "Paper Craft" },
  { value: "Origami", label: "Origami" },
  { value: "Resin Art", label: "Resin Art" },
  { value: "Woodworking", label: "Woodworking" },
  { value: "Glass Painting", label: "Glass Painting" },
  { value: "Hand Embroidery", label: "Hand Embroidery" },
  { value: "Sewing Skills", label: "Sewing Skills" },
  { value: "Knitting", label: "Knitting" },
  { value: "Crochet", label: "Crochet" },
  { value: "Handmade Jewelry", label: "Handmade Jewelry" },
  { value: "Fabric Design", label: "Fabric Design" },
  { value: "Tie Dye Art", label: "Tie Dye Art" },
  { value: "Quilting", label: "Quilting" },
  { value: "Custom Clothing", label: "Custom Clothing" },
  { value: "Macrame", label: "Macrame" },
  { value: "Interior Design", label: "Interior Design" },
  { value: "Home Decor DIY", label: "Home Decor DIY" },
  { value: "Floral Arrangement", label: "Floral Arrangement" },
  { value: "Handmade Furniture", label: "Handmade Furniture" },
  { value: "Pottery Art", label: "Pottery Art" },
  { value: "Candle Making", label: "Candle Making" },
  { value: "Soap Making", label: "Soap Making" },
  { value: "Eco-Friendly Crafts", label: "Eco-Friendly Crafts" },
  { value: "Wall Art", label: "Wall Art" },
  { value: "Upcycling", label: "Upcycling" },
  { value: "DIY Skincare", label: "DIY Skincare" },
  { value: "Natural Beauty Products", label: "Natural Beauty Products" },
  { value: "Handmade Cosmetics", label: "Handmade Cosmetics" },
  { value: "Aromatherapy", label: "Aromatherapy" },
  { value: "Perfume Making", label: "Perfume Making" },
  { value: "Henna Art", label: "Henna Art" },
  { value: "Nail Art Design", label: "Nail Art Design" },
  { value: "Hair Styling", label: "Hair Styling" },
  { value: "Makeup Artistry", label: "Makeup Artistry" },
  { value: "Photography Skills", label: "Photography Skills" },
  { value: "Photo Editing", label: "Photo Editing" },
  { value: "Hand-Drawn Illustrations", label: "Hand-Drawn Illustrations" },
  { value: "Watercolor Art", label: "Watercolor Art" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Graphic Design Basics", label: "Graphic Design Basics" },
  { value: "Portrait Sketching", label: "Portrait Sketching" },
];

export { SkillsArray };
